### ISSUE TITLE
Multi language support 

### ISSUE THREAD

**Issue by keldnorman** [O-MG/O.MG_Cable-Firmware#1]
Hi O.MG, 

Is it possible to select another language before injecting keystrokes ? 

When I inject keystrokes on "users" with DK keyboard then this line: 

http://fakeupdate.net/wnc 

becomes 

httpÆ--fakeupdate.net-wnc

Regards Keld Norman

**Comment by 0xd3d0c3d** [comment]
I don't use a danish keyboard, if you could please show me what keys type wrong for you.. I will go about making a regional DK patch for you. :) So far I see,
1) : mapped to Æ
2) / mapped to -

**Comment by keldnorman** [comment]
Hi, I think the "hard work" have already been done - if you can reuse the methods used on the duckyencoder ( https://github.com/hak5darren/USB-Rubber-Ducky/tree/master/Encoder/resources )  or  Mame82's duck2spark (https://github.com/mame82/duck2spark) 

I think it would be useful to have all languages available as a setting - if there is space enough to hold them in the firmware ? 

What format would you need in order to make a "world" version where a language selection is available ? 

I will try to find it if you tell me what format you need the conversion/mappings in per language.

Best regards
Keld Norman

**Comment by 0xd3d0c3d** [comment]
> Hi, I think the "hard work" have already been done - if you can reuse the methods used on the duckyencoder ( https://github.com/hak5darren/USB-Rubber-Ducky/tree/master/Encoder/resources ) or Mame82's duck2spark (https://github.com/mame82/duck2spark)
> 
> I think it would be useful to have all languages available as a setting - if there is space enough to hold them in the firmware ?
> 
> What format would you need in order to make a "world" version where a language selection is available ?
> 
> I will try to find it if you tell me what format you need the conversion/mappings in per language.
> 
> Best regards
> Keld Norman

thank you, between this information you provided and this site https://www.charset.org/. i believe i will be able to create a system to do this.

**Comment by kevthehermit** [comment]
There is also the python library - https://pypi.org/project/ducktoolkit/

**Comment by eoncom** [comment]
Hi O.MG,
Is it possible to do a French patch?
Thx

**Comment by 0xd3d0c3d** [comment]
i posted a temporary solution for international keyboards on our slack server for the o.mg-cable, if you guys would like please try it out and give feedback.

**Comment by f1x1t1x1f** [comment]
> i posted a temporary solution for international keyboards on our slack server for the o.mg-cable, if you guys would like please try it out and give feedback.

Where can i find the temporary solution?

**Comment by clb92** [comment]
Any news on this since February?

**Comment by spiceywasabi** [comment]
> Any news on this since February?

Hi there! We're working on multi language support but as you can imagine with the new release of hardware and as a result software things are a bit hectic!

**Comment by 0xCCD** [comment]
Is there a branch or early preview we can use for multi language support ?

**Comment by iWolly** [comment]
I need a DE Keyboard layout for the o.mg cables ...

Is there a branch or early preview we can use for multi language support ?

**Comment by 0xCCD** [comment]
> i posted a temporary solution for international keyboards on our slack server for the o.mg-cable, if you guys would like please try it out and give feedback.

How can we get a multi language version or the temporary solution for international keyboard ?

**Comment by OMG-MG** [comment]
All of this was handled via Slack, but I often forget there are some people not in Slack. So here is what you may have missed: The temporary solution is mostly manually remapping the payload syntax. Example: https://github.com/BDDComputing/O.MG_Azerty_to_Qwerty  (you need to only change a single line of that script to updated it for different language layouts).

We expect to release our first attempt at multi-layout support this month in the #omg-cable-advanced-testing channel on our v2 test firmware. Running the v2 firmware requires an upgrade to the cable, so make sure you do that if you haven't already. It's a free upgrade, and the details for running the upgrade are also in #omg-cable-advanced-testing. (Check the pinned items in the channel for details on the latest upgrade tool and v2 test firmware). All of this will be making its way to github as they become more finished. Slack is just easier for getting real time feedback on bugs, and some of the more manual processes.

**Comment by OMG-MG** [comment]
Also, if you want to contribute any maps, this is the repo we are using to store them: https://github.com/O-MG/keymaps
These are just some test maps we are using to make sure the core feature works. Adding additional maps will be pretty easy. We are supporting the DUCKY_LANG method of switching the maps, especially because we are the first 3rd party to officially license DuckyScript from Hak5! All the maps will be built inside the cable storage, and the plan is to have universal maps for both duckyscript payloads, and keylogger. We wanted to do it right :) But that also explains the lag time on getting this all squeezed into the cable, especially during the chaos of 2020.

**Comment by OMG-MG** [comment]
DUCKY_LANG has been added to the v2 firmware. So I am closing this out. 
While v2 is in development, you can find the latest build pinned in the #omg-cable-advanced-testing channel on the Slack server.
