### ISSUE TITLE
Cable becomes unrecognized if unplugged in the middle of a script execution or connection request

### ISSUE THREAD

**Issue by Ash1989** [O-MG/O.MG_Cable-Firmware#12]
I was able to install the firmware easily in station mode and run all the features with no problems. With some further testing, I found that the cable becomes unrecognized if I unplug the cable in the middle of a script execution or any communication in general with the Web UI where I get the message "USB Device not recognized". The only solution for that problem is to install the firmware again which is not practical. Is there a solution or workaround for that issue?.

**Comment by clb92** [comment]
Ah, that's probably how it happened to me too then.

**Comment by OMG-MG** [comment]
Thanks for the report. I hadn't tried this exact failure scenario, but it looks to overlap with the same bug we recently found in dev.

**Comment by OMG-MG** [comment]
@Ash1989 Preemptive question. Not sure it matters but I want to give you some time to respond: can you supply a payload that is able to trigger this for you? Also, was this running off a payload that was saved in the boot slot, one of the other slots, or was it an unsaved payload that you were just running?

**Comment by OMG-MG** [comment]
FYI - We are going to move this to the v2.x firmware

**Comment by OMG-MG** [comment]
This issue should be solved in the v2 firmware. While its in testing, you can find the latest build in the pinned posts of the #omg-cable-advanced-testing channel on the slack server. 
Some attempts to reproduce this issue in the new firmware would be appreciated.
