### ISSUE TITLE
Change device name on Windows

### ISSUE THREAD

**Issue by Aptimex** [O-MG/O.MG_Cable-Firmware#17]
The first time you use the cable to run a script on Windows 10 it  generates a pop-up a message to alert the user that it's setting up 'O.MG-Cable' which is not very conducive to stealth. 
![omg setup](https://user-images.githubusercontent.com/37312852/116336351-9f544d80-a795-11eb-97fc-a617f2d17811.png)

Changing the Description box in the web GUI Settings menu doesn't seem to change that message. It also continues to say "Service: O.MG-Cable" under that box (not sure if that's related or not). 
![omg description](https://user-images.githubusercontent.com/37312852/116336459-d1fe4600-a795-11eb-9a0a-a640c4ac78e8.png)

**Comment by OMG-MG** [comment]
Just saw this. Sorry (most of the support/dev happens on slack so I forget to keep an eye here). 
The settings panel is for changing how the cables presents over the network. I suppose we can add some clarity there. 

For the USB identity, that is all happening via the VID, PID, iManufacturer, iProduct, iSerial identifiers. All of those can be changed on the fly with duckyscript syntax, which allows it to be bound to the specific payload. Just pull up the syntax guide in the web UI for examples. Most people just clone a specific keyboard for this. 
FYI - the cable only presents itself over USB during payload transmission.
