### ISSUE TITLE
v2 Calibration error detected

### ISSUE THREAD

**Issue by prohackzor** [O-MG/O.MG_Cable-Firmware#18]
Hi @ all,
after flashing my O.MG cable via "flash_win64.exe" with the Unified-Firmware 2.0 RC19.1 I setup my WiFi (Access Point mode) with all the settings required, connect to it and browsed to 192.168.4.1.

After that I immediately get the following error message:
![grafik](https://user-images.githubusercontent.com/89911089/131656365-7f38f755-e1ef-4199-866a-e12dda443309.png)
**Log Data: <dc:4f:22:bf:a1:71 - 1M - xc - ?>**

- My browser: Mozilla Firefox 91.0.2 (Brave browser bring's up the same error)
- O.MG cable is directly plugged into USB 3.0 port

So what is the problem here and how can I fix that?

I am grateful for any help!
Best regards

**Comment by OMG-MG** [comment]
There is no "flash_win64.exe" in that v2 firmware build. So that is priobably your issue. But we don't do support on our github. Please join the Slack instance.

**Comment by OMG-MG** [comment]
You can join here: https://github.com/O-MG/O.MG_Cable-Firmware/wiki#support
