### ISSUE TITLE
wifi pass field does not support space characters

### ISSUE THREAD

**Issue by clex25** [O-MG/O.MG_Cable-Firmware#2]
I am attempting to set up the O.MG cable in station mode, using an SSID with a password which contains spaces. When I attempt to do so, the patch fails with error message:

> pi@pigarden:~/development/omg/O.MG_Cable-Firmware-master $ ./flash.sh
> SELECT WIFI MODE: 1) STATION or 2)ACCESS POINT: 1
> ENTER WIFI SSID (limit 32chars): 12341234
> ENTER WIFI PASS (8-64chars): password password
> ./flash.sh: line 21: [: password: binary operator expected
> (ascii art omitted )
> 
> [ mode wrong, length limit is 1 character ]

I think this is failing because of apstation_patch.py line 47: `_mode=sys.argv[3]` - since python uses the space character as a delimiter when parsing arguments. I attempted to use quotes in my input to no avail.

I *am* able to successfully build and flash an image which does not use spaces in the password, so I think the rest of the environment is set up correctly.

I will probably set up a new wifi network without spaces for testing, but thought I'd see if there was a workaround or easy way to patch.

**Comment by O-MG** [comment]
A quick workaround is to just change the wifi settings inside the cable web UI after it comes up. I haven't tested spaces here, but the issue you are hitting is clearly in the flasher routine that is only part of the first setup.

**Comment by 0xd3d0c3d** [comment]
this has been resolved by removing bash entirely. use the static binary flashers or flash.py, spaces are no longer an issue.
