### ISSUE TITLE
Ducky_lang FR , key missing

### ISSUE THREAD

**Issue by PhilSutter** [O-MG/O.MG_Cable-Firmware#42]
Hi guys, 

I'm facing an issue with OMG cable and ducky_lang fr

The key ">" is not working. 
How can i redo the mapping easily ? 

PS : i tried to join your slack support, but i can't. _"This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link."_

Thanks 🙂 

[DIAG] keyToHidMapping: [key]:[>]
[INFO] No keyToHidMapping for (string:>), check DUCKY_LANG mapping
[INFO] ? PAYLOAD HALTED, ERRORS DETECTED

**Comment by kalanihelekunihi** [comment]
Addressed in v2.0-220309
