### ISSUE TITLE
Manufacturer and product variables with spaces are not supported

### ISSUE THREAD

**Issue by c-nagy** [O-MG/O.MG_Cable-Firmware#5]
Hi, first thanks so much for this awesome tool! I'm really impressed with how well it functions and you did a great job with it.

I'm running into an issue when I'm trying to modify the MAN and PRO variables . When the variable contains spaces, such as "Apple Inc." or "Magic Keyboard", it is truncated when being read by the system.

For example:

```
MAN "Apple Inc."
PRO "Magic Keyboard"
SER <Redacted>
VID 05ac
PID 0267
USB ON
DELAY 10
<Rest of payload>
```

With or without quotes, the manufacturer and product values appears to the system as truncated by the first space character: 

![image](https://user-images.githubusercontent.com/3061769/72632631-e9544f80-3913-11ea-9d55-9ba3cb5cd459.png)

If you could add support for multiword variables, as well as ensure that it is possible to fully impersonate an Apple or third-party keyboard without getting a "weird keyboard" prompt on Mac (something I could not figure out after an hour or so), it would be much appreciated! Thanks again for all of your awesome work.

Firmware: v1.4.1 Updated: January 16, 2020

**Comment by O-MG** [comment]
Good catch!  
As for the new keyboard prompt, that dependent on the VID/PID. I have not seen the MAN/PRO/SER  attributes come into play for the built-in OS X detections.  Feel free to jump on the slack server for assistance on that.

**Comment by O-MG** [comment]
Also, see: https://github.com/O-MG/O.MG_Cable-Firmware/issues/6

**Comment by c-nagy** [comment]
Thanks for the quick reply! Adding USB OFF to the top of my payloads fixed the issue of the new keyboard prompt which was my main problem.

**Comment by 0xd3d0c3d** [comment]
I found the problem, no worries. It is also fixed now in the main repo. 
141 SPACE TRUNCATORS
![Screenshot from 2020-01-18 03-46-11](https://user-images.githubusercontent.com/47512843/72661864-20267600-39a5-11ea-8ba7-1c28fbbb73f9.png)

**Comment by c-nagy** [comment]
The fix works great!

<img width="346" alt="fixed" src="https://user-images.githubusercontent.com/3061769/72669434-d8c4d780-39ee-11ea-9225-bc69175f0563.png">

Thanks again
