### ISSUE TITLE
Broken after flashing firmware?

### ISSUE THREAD

**Issue by evildrummer** [O-MG/O.MG_Cable-Firmware#50]
I flashed the firmware with the web flasher and when i replug it without the programmer i run into issues.

After opening the webinterface the OM.G Plug keeps crashing. The USB unplug/replug sounds keeps appearing in a loop.
I doesn´t matter which firmware release i use.

Tried Webflasher with latest driver for the programmer und used a Win 10 latest build and a Win 11 latest build.

\Edit

Also tried different USB Ports (USB 3.2, USB 3.0 and USB 2.0)

**Comment by OMG-MG** [comment]
Please use the support channels for support. We don't do support over github issues.
