### ISSUE TITLE
Unable to connect to cable

### ISSUE THREAD

**Issue by antmar904** [O-MG/O.MG_Cable-Firmware#7]
Hi,

After successfully flashing the cable, I remove the programmer from the usb, plug in the usb cable but I am unable to connect to it while in station mode via http://OMG_LASTSIXOFMACID.local.  Yes I left the last six of the MAC out on purpose.  Thank you for your help

**Comment by O-MG** [comment]
For setup/use help, please hump into the slack server listed on the setup page. https://o.mg.lol/setup
