### ISSUE TITLE
O.MG French Canadian Keyboard

### ISSUE THREAD

**Issue by Xtrem33702** [O-MG/O.MG_Cable-Firmware#8]
Hi

This is the coolest thing i saw since ice age.

Got two issue:

1- My keyboard is in French Canadian - French Canadian so when i inject my email, The @ is changed to ---> ". So can't automate the sending of an email to me whenever I execute the script.

2- The GUI R isn't always send. Got this caracters instead (when i am into notepad++) .

Anything that i can do to fix that or a configuration perharps?

Thank again and nice job :)

**Comment by O-MG** [comment]
This will be handled with the enhancement request here: https://github.com/O-MG/O.MG_Cable-Firmware/issues/1

**Comment by Xtrem33702** [comment]
Ok thanks ! :)
